export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_REPOS = 'GET_REPOS'
export const NO_REPOS = 'NO_REPOS'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

// ADMIN
export const CURRENT_PAGE_SET = 'CURRENT_PAGE_SET'

// APPOINTMENT
export const APPOINTMENTS_LOADED = 'APPOINTMENTS_LOADED'
export const APPOINTMENT_LOADED = 'APPOINTMENT_LOADED'

// PATIENT
export const PATIENTS_LOADED = 'PATIENTS_LOADED'
export const PATIENT_LOADED = 'PATIENT_LOADED'

// NOTE
export const NOTES_LOADED = 'NOTES_LOADED'
export const NOTE_LOADED = 'NOTE_LOADED'